### ISSUE TITLE
 Kindle fire device game stops playing

### ISSUE THREAD

**Issue by shruthims91** [SpringRoll/SpringRoll#89]
Hi,

In the kindle fire device game stops playing when the device is kept idle for sometime(Game is on but not played for some duration). 

When exploring this issue, we got to know that  AudioContext is being initialized based on time condition in the sound.js and this is throwing an error of "Audio Context is undefined".

After commenting the AudioContext line in  _fixAudioContext() method(sound.js), then the issue got resolved  but not sure that this is would be the ideal solution. 

Can this issue be handled in the application without making any changes in sound.js?

**Comment by andrewstart** [comment]
It sounds like the Kindle Fire's Silk browser still has the prefix 'webkit' on the 'AudioContext' class - the bug that _fixAudioContext() is a workaround for shouldn't exist in Silk (or older versions of Chrome on Android), so I'll change how we are seeing if _fixAudioContext() is used so that it doesn't break Silk.

**Comment by andrewstart** [comment]
What version of Fire OS is this Kindle Fire running?

**Comment by thebarge** [comment]
Hi @shruthims91 -
Can you please post the version of Silk and of Fire OS on the affected device(s). To get the Silk version, http://docs.aws.amazon.com/silk/latest/developerguide/troubleshooting.html#version and to get the OS version, http://www.amazon.com/gp/help/customer/display.html?nodeId=201390270&sa-no-redirect=1

**Comment by andrewstart** [comment]
Release 0.4.20 should fix this issue.

**Comment by praveen4565** [comment]
@andrewstart , I am also facing the same issue in kindle fire device(Silk browser). Still facing same issue in 0.4.20 release.
Silk browser version I'm using : 1.0.102.16-Fire_60070210

I am assuming below code is the change you have done in 0.4.20 in Sound.js

function _fixAudioContext()
	{
//close old context
		WebAudioPlugin.context.close();
// Change done in 0.4.20
		var AudioContext = window.AudioContext || window.webkitAudioContext;
		// Reset context
		WebAudioPlugin.context = new AudioContext();

}

When I was debugging I got error in " WebAudioPlugin.context.close();" line. Maybe close() method is unsupported in the silk browser. 



![error](https://cloud.githubusercontent.com/assets/13066894/13047288/0c595846-d404-11e5-8720-5f2b6894a701.PNG)

  I just added try catch block to the "WebAudioPlugin.context.close();"  line, sound started playing and application works fine in silk browser. I know this is not an permanent fix. Please suggest.


function _fixAudioContext()
	{
//close old context
	 try{
	        WebAudioPlugin.context.close();
	    } catch (e) {
	        Debug.error("Custom Error : " + e);
	    }

		var AudioContext = window.AudioContext || window.webkitAudioContext;
		// Reset context
		WebAudioPlugin.context = new AudioContext();

}

**Comment by andrewstart** [comment]
Hmm, it appears that `close()` is a far more recent addition to AudioContext than I thought. Release 0.4.21 should fix this.
